
# @name authenticate
POST https://localhost:4431/connect/token
Content-Type: application/x-www-form-urlencoded
# Authorization: Basic web-portal.client:secret
Authorization: Basic d2ViLXBvcnRhbC5jbGllbnQ6c2VjcmV0

grant_type=password
&scope=openid profile hr.read hr.write manage
&username=admin
&password=Pass123$

###

@access_token = {{authenticate.response.body.token_type}} {{authenticate.response.body.access_token}}
@refresh_token = {{authenticate.response.body.refresh_token}}

###

# @name refresh_token
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded
# Authorization: Basic orquestrador-chamados.client:EEFCE74C-3295-4B6C-B25D-EDD49ABF6953
Authorization: Basic b3JxdWVzdHJhZG9yLWNoYW1hZG9zLmNsaWVudDpFRUZDRTc0Qy0zMjk1LTRCNkMtQjI1RC1FREQ0OUFCRjY5NTM=

grant_type=refresh_token
&refresh_token={{refresh_token}}
