# @name login
POST http://localhost:8081/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=admin-cli
&client_secret=TNrQkFq2Nuzxpgi7QRUug1QJHPJv5GaX

###

@authToken = {{login.response.body.access_token}}

###

# @name get-users
GET http://localhost:8081/admin/realms/nexus/users
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json
