# @name login
POST http://localhost:8081/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=admin-cli
&client_secret=TNrQkFq2Nuzxpgi7QRUug1QJHPJv5GaX

###

POST http://192.168.0.151:8081/realms/nexus/protocol/openid-connect/token
  # -H Authorization: Basic bmV4dXMtY2xpOg==
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=nexus-cli
&username=ritter
&password=pdh82w45

###

@authToken = {{login.response.body.access_token}}

###

# @name get-users
GET http://localhost:8081/admin/realms/nexus/users
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json
