name: nexus

services:
  ravendb:
    image: ravendb/ravendb:ubuntu-latest-lts
    container_name: ravendb.nexus.co
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ravendb-data:/var/lib/ravendb/data

  rabbitmq:
    hostname: "mabbit"
    image: rabbitmq:latest
    container_name: rabbitmq.nexus.co
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-mnesia:/var/lib/rabbitmq/mnesia/

  seq:
    image: datalust/seq:latest
    container_name: seq.nexus.co
    ports:
      - 81:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_PWD_HASH}
    volumes:
      - seq-data:/var/lib/seq/data/

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04"
    container_name: mssql.nexus.co
    hostname: mssql.nexus.co
    user: root
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - mssql-vol:/var/opt/mssql/data

  postgres:
    image: postgres:latest
    container_name: postgres.nexus.co
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "nexus_finance_dev,keycloak"
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./postgresql-create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: keycloak.nexus.co
    hostname: keycloak.nexus.co
    user: root
    ports:
      - "8081:8080"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PWD}
      - KC_DB=postgres
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
    volumes:
      - keycloak-data:/opt/keycloak/data

  finance-api:
    image: ${REGISTRY:-nexus.co}/nexus/finance-api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: finance-api.nexus.co
    restart: always
    build:
      context: .
      dockerfile: src/Finance/Nexus.Finance.Api/Dockerfile
    ports:
      - "8002:80"
      - "4432:443"

  finance-worker:
    image: ${REGISTRY:-nexus.co}/nexus/finance-worker:${PLATFORM:-linux}-${TAG:-latest}
    container_name: finance-worker.nexus.co
    restart: always
    build:
      context: .
      dockerfile: src/Finance/Nexus.Finance.Worker/Dockerfile
    ports:
      - "8003:80"
      - "4433:443"

volumes:
  mssql-vol:
    name: nexus.co.mssql-data-vol
  postgres-vol:
    name: nexus.co.postgres-vol
  ravendb-config:
    name: nexus.co.ravendb-config-vol
  ravendb-data:
    name: nexus.co.ravendb-data-vol
  seq-data:
    name: nexus.co.seq-vol
  keycloak-data:
    name: nexus.co.keycloak-vol
  rabbitmq-data:
    name: nexus.co.rabbitmq-data-vol
  rabbitmq-mnesia:
    name: nexus.co.rabbitmq-mnesia-vol
