name: nexus

services:
  ravendb:
    image: ravendb/ravendb:ubuntu-latest-lts
    container_name: ravendb.nexus.ritter.co
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData

  rabbitmq:
    hostname: "mabbit"
    image: rabbitmq:latest
    container_name: rabbitmq.nexus.ritter.co
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-mnesia:/var/lib/rabbitmq/mnesia/

  seq:
    image: datalust/seq:latest
    container_name: seq.nexus.ritter.co
    ports:
      - 81:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_PWD_HASH}
    volumes:
      - seq-data:/var/lib/seq/data/

  postgres:
    image: postgres:latest
    container_name: postgres.nexus.ritter.co
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "nexus_core_dev,keycloak"
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./postgresql-create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: keycloak.nexus.ritter.co
    hostname: keycloak.ritter.co
    user: root
    ports:
      - "8081:8080"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PWD}
      - KC_DB=postgres
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
    volumes:
      - keycloak-data:/opt/keycloak/data

  core-api:
    image: ${REGISTRY:-ritter.co}/nexus/core-api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: core-api.nexus.ritter.co
    restart: always
    build:
      context: .
      dockerfile: src/Core/Nexus.Core.Api/Dockerfile
    ports:
      - "8002:80"
      - "4432:443"

  core-worker:
    image: ${REGISTRY:-ritter.co}/nexus/core-worker:${PLATFORM:-linux}-${TAG:-latest}
    container_name: core-worker.nexus.ritter.co
    restart: always
    build:
      context: .
      dockerfile: src/Core/Nexus.Core.Worker/Dockerfile
    ports:
      - "8003:80"
      - "4433:443"

volumes:
  mysql-vol:
    name: ritter.co-nexus-mysql-vol
    external: true
  postgres-vol:
    name: ritter.co-nexus-postgres-vol
  ravendb-config:
    name: ritter.co-nexus-ravendb-config-vol
    external: true
  ravendb-data:
    name: ritter.co-nexus-ravendb-data-vol
    external: true
  seq-data:
    name: ritter.co-nexus-seq-vol
    external: true
  keycloak-data:
    name: ritter.co-nexus-keycloak-vol
    external: true
  rabbitmq-data:
    name: ritter.co-nexus-rabbitmq-data-vol
    external: true
  rabbitmq-mnesia:
    name: ritter.co-nexus-rabbitmq-mnesia-vol
    external: true
