services:
  rabbitmq:
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      retries: 20

  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    depends_on:
      mysql:
        condition: service_healthy
        restart: true

  core-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DbProvider=Npgsql
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=nexus_core_dev;Persist Security Info=False;User ID=${MSSQL_USER_ID};Password=${MSSQL_PASSWORD};MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
      - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
      - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://${RMQ_USER}:${RMQ_PWD}@rabbitmq:5672
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=4432
      - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
      - ASPNETCORE_RavenSettings__DatabaseName=NexusCore
      - ASPNETCORE_RavenSettings__CertFilePath=
      - ASPNETCORE_RavenSettings__CertPassword=
      - ASPNETCORE_Keycloak__Realm=nexus
      - ASPNETCORE_Keycloak__AuthServerUrl=http://192.168.0.175:8081
      - ASPNETCORE_Keycloak__SslRequired=none
      - ASPNETCORE_Keycloak__Resource=nexus-cli
      - ASPNETCORE_Keycloak__VerifyTokenAudience=true
      - ASPNETCORE_Keycloak__Scopes=email profile nexus-ui-client-scope
      - ASPNETCORE_Keycloak__ConfidentialPort=0
      - ASPNETCORE_UiAvatars__BaseAddress=https://ui-avatars.com/api
      - ASPNETCORE_UiAvatars__DefaultBackground=0D8ABC
      - ASPNETCORE_UiAvatars__DefaultColor=FFF
      - ASPNETCORE_Cors__Origins=https://localhost:4432;http://localhost:8002;http://localhost:4200
    volumes:
      - ~/.microsoft/usersecrets\:/root/.microsoft/usersecrets
      - ~/.aspnet/https:/root/.aspnet/https/
      - ~/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys/
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      ravendb:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true

  core-worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DbProvider=Npgsql
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=nexus_core_dev;Persist Security Info=False;User ID=${MSSQL_USER_ID};Password=${MSSQL_PASSWORD};MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
      - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
      - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://${RMQ_USER}:${RMQ_PWD}@rabbitmq:5672
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=4433
      - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
      - ASPNETCORE_RavenSettings__DatabaseName=NexusCore
      - ASPNETCORE_RavenSettings__CertFilePath=
      - ASPNETCORE_RavenSettings__CertPassword=
      - ASPNETCORE_Cors__Origins=https://localhost:4433;http://localhost:8003;http://localhost:4200
    volumes:
      - ~/.microsoft/usersecrets\:/root/.microsoft/usersecrets
      - ~/.aspnet/https:/root/.aspnet/https/
      - ~/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys/
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      ravendb:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
