// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Finance.Infra.Data;

#nullable disable

namespace Nexus.Finance.Infra.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20241118013409_02")]
    partial class _02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Finance.Domain.Customers.Aggregates.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Type")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People", "Finance");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Complement")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAddresses", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.HasIndex("PersonId", "TypeId", "Number")
                        .IsUnique();

                    b.ToTable("PersonDocuments", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonDocumentType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PersonDocumentTypes", (string)null);
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonEmail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "MailAddress")
                        .IsUnique();

                    b.ToTable("PersonEmails", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonPhone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "CountryCode", "Number")
                        .IsUnique();

                    b.ToTable("PersonPhones", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.LegalPerson", b =>
                {
                    b.HasBaseType("Nexus.Finance.Domain.People.Aggregates.Person");

                    b.Property<DateOnly?>("OpenedAt")
                        .HasColumnType("date");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Nexus.Finance.Domain.People.Aggregates.LegalPerson.Name#LegalPersonName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BrandName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("BrandName");

                            b1.Property<string>("CorporateName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("CorporateName");
                        });

                    b.ToTable("LegalPeople", (string)null);
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.NaturalPerson", b =>
                {
                    b.HasBaseType("Nexus.Finance.Domain.People.Aggregates.Person");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Nexus.Finance.Domain.People.Aggregates.NaturalPerson.Name#NaturalPersonName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("LastName");
                        });

                    b.ToTable("NaturalPeople", (string)null);
                });

            modelBuilder.Entity("Nexus.Finance.Domain.Users.Aggregates.User", b =>
                {
                    b.HasBaseType("Nexus.Finance.Domain.People.Aggregates.NaturalPerson");

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.ToTable("Users", "Finance");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonAddress", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonDocument", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", "Person")
                        .WithMany("Documents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.PersonDocumentType", "Type")
                        .WithMany("Documents")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonEmail", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", "Person")
                        .WithMany("Emails")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonPhone", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.LegalPerson", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", null)
                        .WithOne()
                        .HasForeignKey("Nexus.Finance.Domain.People.Aggregates.LegalPerson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.NaturalPerson", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.Person", null)
                        .WithOne()
                        .HasForeignKey("Nexus.Finance.Domain.People.Aggregates.NaturalPerson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Finance.Domain.Users.Aggregates.User", b =>
                {
                    b.HasOne("Nexus.Finance.Domain.People.Aggregates.NaturalPerson", null)
                        .WithOne()
                        .HasForeignKey("Nexus.Finance.Domain.Users.Aggregates.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Documents");

                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Nexus.Finance.Domain.People.Aggregates.PersonDocumentType", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
